version: "2"

run:
  timeout: 30m
  tests: false

linters:
  default: none
  enable:
    - ineffassign
    - nakedret
    - revive
    - staticcheck   # 已包含原 stylecheck / gosimple
    - unconvert
    - unparam
    - unused
  settings:        # 原 linters-settings 整体搬到这里
    nakedret:
      max-func-lines: 5
    revive:
      severity: error
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: context-keys-type
        - name: error-strings
        - name: var-naming
          arguments:
            - []               # allow 列表（空表示用默认）
            - ["GRPC", "WAL"]  # deny  列表
        # 下面两条先关闭，后续可分批打开
        - name: exported
          disabled: true
        - name: unexported-return
          disabled: true
    staticcheck:
      checks:
        - "all"
        - "-SA1019"   # 去掉已弃用 API 提醒
        - "-SA2002"   # 去掉测试 goroutine 内调 FailNow 提醒

# ===============  格式化工具  ===============
formatters:
  enable:
    - goimports   # 原 linters 中的 goimports 移到这里
    